
package com.mycompany.sistema_monitereador_energia.view;

import com.mycompany.sistema_monitereador_energia.model.Dispositivo;
import com.mycompany.sistema_monitereador_energia.repository.MysqldispositivoRepository;
import com.mycompany.sistema_monitereador_energia.service.DispositivoService;
import com.mycompany.sistema_monitereador_energia.service.UsuarioService;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;


public class Frmgraficos_consumo extends javax.swing.JFrame {

    
    public Frmgraficos_consumo() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaReporte = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnreporte = new javax.swing.JButton();
        panelGraficos = new javax.swing.JPanel();
        btngraficar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1030, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txaReporte.setColumns(20);
        txaReporte.setRows(5);
        jScrollPane1.setViewportView(txaReporte);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 271, 254));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("REPORTE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("HISTORIAL DE CONSUMO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        btnreporte.setText("MOSTRAR REPORTE");
        btnreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnreporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, -1, 42));

        javax.swing.GroupLayout panelGraficosLayout = new javax.swing.GroupLayout(panelGraficos);
        panelGraficos.setLayout(panelGraficosLayout);
        panelGraficosLayout.setHorizontalGroup(
            panelGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        panelGraficosLayout.setVerticalGroup(
            panelGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        getContentPane().add(panelGraficos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 270));

        btngraficar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btngraficar.setText("GRAFICAR");
        btngraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngraficarActionPerformed(evt);
            }
        });
        getContentPane().add(btngraficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private JPanel crearGraficoCircular(List<Dispositivo> dispositivos) {
    DefaultPieDataset dataset = new DefaultPieDataset();
    for (Dispositivo dispositivo : dispositivos) {
        dataset.setValue(dispositivo.getTipo(), dispositivo.getConsumoActual());
    }

    JFreeChart chart = ChartFactory.createPieChart(
        "Consumo Actual por Dispositivo",
        dataset,
        true,
        true,
        false
            
    );
    ChartPanel chartPanel = new ChartPanel(chart);
    chartPanel.setPreferredSize(new java.awt.Dimension(300, 300)); 

    return chartPanel;
}
    
    private JPanel crearGraficoBarras(List<Dispositivo> dispositivos) {
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();
    for (Dispositivo dispositivo : dispositivos) {
        dataset.addValue(dispositivo.getConsumoActual(), "Consumo Actual", dispositivo.getTipo());
        dataset.addValue(dispositivo.getConsumoEstimado(), "Consumo Estimado", dispositivo.getTipo());
    }

    JFreeChart chart = ChartFactory.createBarChart(
        "Comparación de Consumo por Dispositivo",
        "Dispositivos",
        "Consumo (Horas)",
        dataset,
        PlotOrientation.HORIZONTAL,
        true,
        true,
        false
    );
    ChartPanel chartPanel = new ChartPanel(chart);
    chartPanel.setPreferredSize(new java.awt.Dimension(300, 300)); 

    return chartPanel;
}
    
    private void btngraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngraficarActionPerformed
        int usuarioId = UsuarioService.getInstance().obtenerUsuarioActual().getId();
        DispositivoService dispositivoService = new DispositivoService(new MysqldispositivoRepository());
        List<Dispositivo> dispositivos = dispositivoService.obtenerDispositivosUsuario(usuarioId);

        JPanel panelCircular = crearGraficoCircular(dispositivos);
        JPanel panelBarras = crearGraficoBarras(dispositivos);
        
        panelCircular.setBounds(50, 50, 300, 300);
        panelBarras.setBounds(400, 50, 300, 300);
        
        panelGraficos.removeAll(); 
        panelGraficos.setLayout(new GridLayout(1, 2)); 
        panelGraficos.add(panelCircular);
        panelGraficos.add(panelBarras);
        panelGraficos.revalidate();
        panelGraficos.repaint();
    }//GEN-LAST:event_btngraficarActionPerformed

    private void btnreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteActionPerformed
        int usuarioId = UsuarioService.getInstance().obtenerUsuarioActual().getId();
        DispositivoService dispositivoService = new DispositivoService(new MysqldispositivoRepository());
        List<Dispositivo> dispositivos = dispositivoService.obtenerDispositivosUsuario(usuarioId);

    generarReporte(dispositivos);
    }//GEN-LAST:event_btnreporteActionPerformed
    
    private void generarReporte(List<Dispositivo> dispositivos) {
    double consumoTotalActual = 0;
    double consumoTotalEstimado = 0;

    for (Dispositivo dispositivo : dispositivos) {
        consumoTotalActual += dispositivo.getConsumoActual();
        consumoTotalEstimado += dispositivo.getConsumoEstimado();
    }

    StringBuilder reporte = new StringBuilder();
    reporte.append("Consumo Total Actual: ").append(consumoTotalActual).append(" horas\n");
    reporte.append("Consumo Total Estimado: ").append(consumoTotalEstimado).append(" horas\n");

    if (consumoTotalActual > consumoTotalEstimado) {
        reporte.append("Recomendación: Reduce el uso de los \ndispositivos con mayor consumo.\n");
    } else {
        reporte.append("Recomendación: El consumo actual está \ndentro de los límites normales.\n");
    }

    txaReporte.setText(reporte.toString()); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmgraficos_consumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmgraficos_consumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmgraficos_consumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmgraficos_consumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmgraficos_consumo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btngraficar;
    private javax.swing.JButton btnreporte;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelGraficos;
    private javax.swing.JTextArea txaReporte;
    // End of variables declaration//GEN-END:variables
}
