
package com.mycompany.sistema_monitereador_energia.view;

import com.mycompany.sistema_monitereador_energia.model.Usuario;
import com.mycompany.sistema_monitereador_energia.service.UsuarioService;
import javax.swing.JOptionPane;


public class FrmModificar_Datos_usuario extends javax.swing.JFrame {

    
    public FrmModificar_Datos_usuario() {
        initComponents();
        int usuarioId = UsuarioService.getInstance().obtenerUsuarioActual().getId();
        Usuario usuario = UsuarioService.getInstance().obtenerUsuario(usuarioId);
        
        if (usuario != null) {
        lblnombrausuario.setText(usuario.getNombre()); 
        lblcontrasena.setText(usuario.getContrasena()); 
    }
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblnombrausuario = new javax.swing.JLabel();
        lblcontrasena = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtModificarNombre = new javax.swing.JTextField();
        txtModificarContrasena = new javax.swing.JTextField();
        btnActualizarDatos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaReporte = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre Actual:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 125, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("MODIFICAR DATOS DE USUARIO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 41, -1, -1));

        jLabel3.setText("Contraseña Actual:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 176, -1, -1));

        lblnombrausuario.setText("nombre");
        getContentPane().add(lblnombrausuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 125, -1, -1));

        lblcontrasena.setText("contraseña");
        getContentPane().add(lblcontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 176, -1, -1));

        jLabel6.setText("Modificar Nombre:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 244, -1, -1));

        jLabel7.setText("Modificar Contraseña:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 306, -1, -1));
        getContentPane().add(txtModificarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 241, 147, -1));
        getContentPane().add(txtModificarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 303, 147, -1));

        btnActualizarDatos.setText("ACTUALIZAR DATOS");
        btnActualizarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 413, -1, -1));

        txaReporte.setColumns(20);
        txaReporte.setRows(5);
        jScrollPane1.setViewportView(txaReporte);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 168, 177, 158));

        jLabel8.setText("Reporte de cambios:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 134, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarDatosActionPerformed
        try {
        int usuarioId = UsuarioService.getInstance().obtenerUsuarioActual().getId();
        String nuevoNombre = txtModificarNombre.getText();
        String nuevaContrasena = txtModificarContrasena.getText();

        Usuario usuario = new Usuario(usuarioId, nuevoNombre, nuevaContrasena);

        UsuarioService.getInstance().actualizarUsuario(usuario);

        // Mostrar reporte de cambios
        txaReporte.setText("Datos actualizados correctamente:\n" +
                                  "Nuevo Nombre: " + nuevoNombre + "\n" +
                                  "Contraseña actualizada: " + nuevaContrasena + "\n");
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error al actualizar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
        
        
    }//GEN-LAST:event_btnActualizarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmModificar_Datos_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmModificar_Datos_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmModificar_Datos_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmModificar_Datos_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmModificar_Datos_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcontrasena;
    private javax.swing.JLabel lblnombrausuario;
    private javax.swing.JTextArea txaReporte;
    private javax.swing.JTextField txtModificarContrasena;
    private javax.swing.JTextField txtModificarNombre;
    // End of variables declaration//GEN-END:variables
}
