
package com.mycompany.sistema_monitereador_energia.view;

import com.mycompany.sistema_monitereador_energia.factory.DatabaseConnection;
import com.mycompany.sistema_monitereador_energia.model.DatabaseType;
import com.mycompany.sistema_monitereador_energia.repository.DispositivoRepositoryPostgre;
import com.mycompany.sistema_monitereador_energia.repository.MysqldispositivoRepository;
import com.mycompany.sistema_monitereador_energia.service.DispositivoService;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class FrmRegistro_Dispositivos extends javax.swing.JFrame {
    
    private final DispositivoService dispositivoService;
     
    public FrmRegistro_Dispositivos() {
        initComponents();
         dispositivoService = new DispositivoService(new MysqldispositivoRepository());
         setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txttipodispositivo = new javax.swing.JTextField();
        txtconsumoestimado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtconsumoactual = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrarDispositivos = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 460));
        setMinimumSize(new java.awt.Dimension(550, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tipo de dispositivo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));
        getContentPane().add(txttipodispositivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 160, -1));
        getContentPane().add(txtconsumoestimado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 160, -1));

        jLabel4.setText("Ingrese su consumo actual en Horas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));
        getContentPane().add(txtconsumoactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 160, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel6.setText("Ingrese su consumo estimado en Horas");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("REGISTRO DISPOSITIVOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        btnRegistrarDispositivos.setText("REGISTRAR");
        btnRegistrarDispositivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDispositivosActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarDispositivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        btnsalir.setText("VOLVER");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarDispositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDispositivosActionPerformed
        try {
            String tipo = txttipodispositivo.getText();
            String consumoEstimadoStr = txtconsumoestimado.getText();
            String consumoActualStr = txtconsumoactual.getText();

        if (tipo.isEmpty() || consumoEstimadoStr.isEmpty() || consumoActualStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
                return; 
            }
         
        double consumoEstimado;
        double consumoActual;

        try {
            consumoEstimado = Double.parseDouble(consumoEstimadoStr);
            consumoActual = Double.parseDouble(consumoActualStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos para el consumo estimado y el consumo actual.");
            return;
        }
            
            
            dispositivoService.registrarDispositivo(tipo, consumoEstimado, consumoActual);
            JOptionPane.showMessageDialog(this, "Dispositivo registrado con éxito");

            txttipodispositivo.setText("");
            txtconsumoestimado.setText("");
            txtconsumoactual.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos para el consumo", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al registrar el dispositivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarDispositivosActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
       dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro_Dispositivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro_Dispositivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro_Dispositivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro_Dispositivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistro_Dispositivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarDispositivos;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtconsumoactual;
    private javax.swing.JTextField txtconsumoestimado;
    private javax.swing.JTextField txttipodispositivo;
    // End of variables declaration//GEN-END:variables
}
