
package com.mycompany.sistema_monitereador_energia.view;

import com.mycompany.sistema_monitereador_energia.factory.UsuarioRepositoryFactory;
import com.mycompany.sistema_monitereador_energia.model.DatabaseType;
import com.mycompany.sistema_monitereador_energia.model.Usuario;
import com.mycompany.sistema_monitereador_energia.repository.UsuarioRepository;
import com.mycompany.sistema_monitereador_energia.repository.UsuarioRepositoryPostgre;
import com.mycompany.sistema_monitereador_energia.service.UsuarioService;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;




public class FrmRegistro_usuario extends javax.swing.JFrame {

    private final UsuarioService usuarioService;
    
    public FrmRegistro_usuario() {
        initComponents();
        DatabaseType tipoBaseDatos = DatabaseType.MYSQL; // Puedes cambiar el tipo de base de datos según se requiera
        usuarioService = UsuarioService.getInstance(UsuarioRepositoryFactory.getRepository(tipoBaseDatos));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtregistrocontraseña = new javax.swing.JTextField();
        txtregistronombreusuario = new javax.swing.JTextField();
        btnregistrar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cmbDatabaseType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(73, 181, 172));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SISTEMA DE ENERGIA ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 48, -1, -1));

        txtregistrocontraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtregistrocontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 257, 290, 50));

        txtregistronombreusuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtregistronombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 158, 290, 50));

        btnregistrar.setBackground(new java.awt.Color(33, 45, 62));
        btnregistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnregistrar.setText("REGISTRAR");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 453, -1, 49));

        btnsalir.setBackground(new java.awt.Color(33, 45, 62));
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setText("CANCELAR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 455, -1, 45));

        jLabel16.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Seleccion la base de datos");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 343, -1, -1));

        jLabel17.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("NOMBRE DE USUARIO");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 133, -1, -1));

        jLabel18.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("CONTRASEÑA");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 236, -1, -1));

        cmbDatabaseType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MySQL", "PostgreSQL", "TextFile" }));
        jPanel1.add(cmbDatabaseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        
        String nombre = txtregistronombreusuario.getText();
        String contrasena = txtregistrocontraseña.getText();
        
        if (nombre.isEmpty() || contrasena.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
        return; 
    }
        String selectedDb = (String) cmbDatabaseType.getSelectedItem();
        DatabaseType dbType;
        
        switch (selectedDb) {
        case "MySQL" -> dbType = DatabaseType.MYSQL;
        case "PostgreSQL" -> dbType = DatabaseType.POSTGRESQL;
        case "TextFile" -> dbType = DatabaseType.TEXTFILE;
        default -> {
            JOptionPane.showMessageDialog(this, "Tipo de base de datos no válido.");
            return;
        }
    }
        
        UsuarioRepository usuarioRepo = UsuarioRepositoryFactory.getRepository(dbType);
        UsuarioService usuarioService = UsuarioService.getInstance(usuarioRepo);
        
        
        Usuario usuario = new Usuario();
        usuario.setNombre(nombre);
        usuario.setContrasena(contrasena);
        
        try {
            usuarioService.agregarUsuario(usuario);
            JOptionPane.showMessageDialog(this, "Usuario registrado con éxito");
            limpiar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al registrar usuario: " + ex.getMessage());
        }
        
        limpiar();
        
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
       dispose();
    }//GEN-LAST:event_btnsalirActionPerformed
    
    public void limpiar(){
        txtregistrocontraseña.setText("");
        txtregistronombreusuario.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistro_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cmbDatabaseType;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtregistrocontraseña;
    private javax.swing.JTextField txtregistronombreusuario;
    // End of variables declaration//GEN-END:variables
}
