
package com.mycompany.sistema_monitereador_energia.view;


public class FrmSistema_monitoreo extends javax.swing.JFrame {

    /**
     * Creates new form FrmSistema_monitoreo
     */
    public FrmSistema_monitoreo() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        lblnombreusuario = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MnuSalir = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MnuRegistroDispositivos = new javax.swing.JMenuItem();
        MnuMisDispositivos = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mnuGraficosconsumo = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        MnuModificarDatos = new javax.swing.JMenuItem();

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu11.setText("jMenu11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblnombreusuario.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblnombreusuario.setText("User");
        lblnombreusuario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblnombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, -1, -1));
        lblnombreusuario.getAccessibleContext().setAccessibleName("jLabel2\n");

        jMenu3.setText("INICIO");

        jMenuItem1.setText("Principal");
        jMenu3.add(jMenuItem1);

        MnuSalir.setText("Salir");
        MnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuSalirActionPerformed(evt);
            }
        });
        jMenu3.add(MnuSalir);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("DISPOSITIVOS");

        MnuRegistroDispositivos.setText("Registro Dispositivos");
        MnuRegistroDispositivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuRegistroDispositivosActionPerformed(evt);
            }
        });
        jMenu4.add(MnuRegistroDispositivos);

        MnuMisDispositivos.setText("Mis Dispositivos");
        MnuMisDispositivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuMisDispositivosActionPerformed(evt);
            }
        });
        jMenu4.add(MnuMisDispositivos);

        jMenuBar2.add(jMenu4);

        jMenu7.setText("CONSUMO");

        mnuGraficosconsumo.setText("Graficos de consumo");
        mnuGraficosconsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGraficosconsumoActionPerformed(evt);
            }
        });
        jMenu7.add(mnuGraficosconsumo);

        jMenuBar2.add(jMenu7);

        jMenu8.setText("OPCIONES");

        MnuModificarDatos.setText("Modificar datos Usuario");
        MnuModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuModificarDatosActionPerformed(evt);
            }
        });
        jMenu8.add(MnuModificarDatos);

        jMenuBar2.add(jMenu8);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuSalirActionPerformed
        dispose();
    }//GEN-LAST:event_MnuSalirActionPerformed

    private void MnuRegistroDispositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuRegistroDispositivosActionPerformed
        FrmRegistro_Dispositivos frm_regis = new FrmRegistro_Dispositivos();
        frm_regis.setVisible(true);
        frm_regis.setLocationRelativeTo(this);
        
    }//GEN-LAST:event_MnuRegistroDispositivosActionPerformed

    private void MnuMisDispositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuMisDispositivosActionPerformed
        FrmMis_Dispositivos frm_mis = new FrmMis_Dispositivos();
        frm_mis.setVisible(true);
        frm_mis.setLocationRelativeTo(null);
    }//GEN-LAST:event_MnuMisDispositivosActionPerformed

    private void mnuGraficosconsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGraficosconsumoActionPerformed
        Frmgraficos_consumo frm_gra = new Frmgraficos_consumo();
        frm_gra.setVisible(true);
        frm_gra.setLocationRelativeTo(null);
    }//GEN-LAST:event_mnuGraficosconsumoActionPerformed

    private void MnuModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuModificarDatosActionPerformed
        FrmModificar_Datos_usuario frm_mod = new FrmModificar_Datos_usuario();
        frm_mod.setVisible(true);
        frm_mod.setLocationRelativeTo(null);
    }//GEN-LAST:event_MnuModificarDatosActionPerformed
    
     public void setNombreUsuario(String nombre) {
        lblnombreusuario.setText("Bienvenido, " + nombre);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSistema_monitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSistema_monitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSistema_monitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSistema_monitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSistema_monitoreo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuMisDispositivos;
    private javax.swing.JMenuItem MnuModificarDatos;
    private javax.swing.JMenuItem MnuRegistroDispositivos;
    private javax.swing.JMenuItem MnuSalir;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblnombreusuario;
    private javax.swing.JMenuItem mnuGraficosconsumo;
    // End of variables declaration//GEN-END:variables
}
